// angular/src/app/shared/components/cover-image/cover-image.component.ts
import { 
  ChangeDetectionStrategy, 
  Component, 
  computed, 
  input, 
  signal, 
  viewChild, 
  afterNextRender, 
  ElementRef, 
  OnDestroy,
  effect,
  untracked
} from '@angular/core';
import { NgStyle } from '@angular/common';

@Component({
  selector: 'app-cover-image',
  standalone: true,
  imports: [NgStyle],
  template: `
    <span #holder class="cover-holder">
      @if (showImage()) {
        <img
          [src]="src()"
          [alt]="alt()"
          [class.cover-loading]="!imageLoaded()"
          (load)="imageLoaded.set(true)"
          (error)="errored.set(true)"
        />
      }
      
      @if (!showImage() || !imageLoaded()) {
        <div class="cover-fallback" [ngStyle]="fallbackStyle()">
          <span>{{ alt() || 'No cover' }}</span>
        </div>
      }
    </span>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CoverImageComponent implements OnDestroy {
  readonly src = input<string | null | undefined>(null);
  readonly alt = input<string>('');
  readonly lazy = input<boolean>(true);

  readonly holder = viewChild.required<ElementRef<HTMLElement>>('holder');

  readonly shouldLoad = signal(false);
  readonly errored = signal(false);
  readonly imageLoaded = signal(false);

  readonly showImage = computed(() =>
    this.shouldLoad() && !!this.src() && !this.errored()
  );

  private observer: IntersectionObserver | null = null;
  private timeoutId: any = null;

  constructor() {
    // Reset state whenever src changes
    effect(() => {
      this.src(); // Track input change
      untracked(() => {
        this.errored.set(false);
        this.imageLoaded.set(false);
        this.clearTimeout();
        if (this.shouldLoad()) this.startTimeout();
      });
    });

    // Start timeout when shouldLoad flips to true
    effect(() => {
      if (this.shouldLoad()) {
        untracked(() => this.startTimeout());
      }
    });

    afterNextRender(() => {
      if (!this.lazy() || typeof IntersectionObserver === 'undefined') {
        this.shouldLoad.set(true);
        return;
      }

      this.observer = new IntersectionObserver((entries) => {
        if (entries[0]?.isIntersecting) {
          this.shouldLoad.set(true);
          this.disconnectObserver();
        }
      }, { rootMargin: '120px' });

      this.observer.observe(this.holder().nativeElement);
    });
  }

  ngOnDestroy(): void {
    this.disconnectObserver();
    this.clearTimeout();
  }

  private startTimeout(): void {
    this.clearTimeout();
    if (!this.src()) return;
    
    this.timeoutId = setTimeout(() => {
      if (!this.imageLoaded()) {
        this.errored.set(true);
      }
    }, 3000);
  }

  private clearTimeout(): void {
    if (this.timeoutId) {
      clearTimeout(this.timeoutId);
      this.timeoutId = null;
    }
  }

  private disconnectObserver(): void {
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }
  }

  private hashHue(text: string): number {
    let hash = 0;
    for (let i = 0; i < text.length; i++) {
      hash = (hash << 5) - hash + text.charCodeAt(i);
      hash |= 0;
    }
    return Math.abs(hash) % 360;
  }

  readonly fallbackStyle = computed(() => {
    const text = this.alt() || 'cover';
    const hue = this.hashHue(text);
    return {
      background: `linear-gradient(135deg, hsl(${hue} 60% 35%), hsl(${(hue + 30) % 360} 60% 45%))`,
    };
  });
}

// frontend/src/components/CoverImage.jsx
import { useEffect, useMemo, useRef, useState } from 'react'

function hashHue(text = '') {
  let hash = 0
  for (let i = 0; i < text.length; i += 1) {
    hash = (hash << 5) - hash + text.charCodeAt(i)
    hash |= 0 // keep 32-bit int
  }
  return Math.abs(hash) % 360
}

function CoverImage({ src, title, alt, className = '', style = {}, lazy = true }) {
  const holderRef = useRef(null)
  const [shouldLoad, setShouldLoad] = useState(!lazy)
  const [errored, setErrored] = useState(false)
  const label = title || alt || 'No cover'
  const hue = useMemo(() => hashHue(label), [label])
  const fallbackStyle = {
    background: `linear-gradient(135deg, hsl(${hue} 60% 35%), hsl(${(hue + 30) % 360} 60% 45%))`,
    ...style,
  }

  useEffect(() => {
    if (!lazy) return
    const el = holderRef.current
    if (!el || typeof IntersectionObserver === 'undefined') {
      // If IntersectionObserver not available, load immediately in next tick
      const timer = setTimeout(() => setShouldLoad(true), 0)
      return () => clearTimeout(timer)
    }
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          setShouldLoad(true)
          observer.disconnect()
        }
      })
    }, { rootMargin: '120px' })
    observer.observe(el)
    return () => observer.disconnect()
  }, [lazy])

  const showImage = shouldLoad && src && !errored

  return (
    <span ref={holderRef} className="cover-holder">
      {showImage ? (
        <img
          className={`cover-image ${className}`}
          src={src}
          alt={alt || title || 'Cover image'}
          onError={() => setErrored(true)}
          style={style}
          loading="lazy"
        />
      ) : (
        <div className={`cover-fallback ${className}`} style={fallbackStyle}>
          <span>{label}</span>
        </div>
      )}
    </span>
  )
}

export default CoverImage
