// frontend/src/components/BookCard.jsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { STATUS, truncateText, scoreToLabel } from '../lib/db.js'
import CoverImage from './CoverImage.jsx'

/**
 * BookCard Component
 * 
 * Displays a single book with:
 * - Cover image, title, description
 * - Status and metadata pills
 * - Latest chapter info
 * - Links to sources and book details
 * - Optional shelf management (for Bookshelf view)
 * 
 * @param {Object} props
 * @param {Object} props.book - Book data
 * @param {Function} props.onAddToShelf - Optional callback when shelf is toggled
 * @param {Array} props.customShelves - Optional list of custom shelves
 * @param {Array} props.activeGenres - Optional list of active genre filters
 * @param {Function} props.setActiveGenres - Optional callback to update genre filters
 * @param {boolean} props.compact - If true, shows simpler version (Dashboard mode)
 */
function BookCard({
  book,
  onAddToShelf,
  customShelves = [],
  activeGenres = [],
  setActiveGenres,
  compact = false,
}) {
  const [showShelfMenu, setShowShelfMenu] = useState(false)

  const scoreColor = (score) => {
    const n = Number(score)
    if (!Number.isFinite(n)) return 'var(--text)'
    if (n >= 9) return '#b34ad3ff'   // great/masterpiece
    if (n >= 7) return '#0ba360'   // good/pretty good
    if (n >= 5) return '#c6a700'   // average/fine
    if (n >= 3) return '#d97706'   // bad/pretty bad
    if (n >= 1) return '#d14343'   // appalling/horrible
    return '#ffffff'               // 0 / N/A
  }

  const languageFlag = (lang) => {
    if (!lang) return null
    const lower = lang.toLowerCase()
    if (lower.startsWith('eng') || lower === 'en' || lower === 'english') return '🇬🇧'
    if (lower.startsWith('jap') || lower === 'jp' || lower === 'ja' || lower === 'jpn') return '🇯🇵'
    if (lower.startsWith('kor') || lower === 'kr' || lower === 'ko') return '🇰🇷'
    if (lower.startsWith('chi') || lower.includes('mandarin') || lower === 'cn' || lower === 'zh') return '🇨🇳'
    if (lower.startsWith('spa') || lower === 'es') return '🇪🇸'
    return null
  }

  const handleToggleShelf = (shelfId) => {
    if (onAddToShelf) {
      onAddToShelf(book.id, shelfId)
      setShowShelfMenu(false)
    }
  }

  return (
    <article className="card" style={{ zIndex: showShelfMenu ? 50 : 0 }}>
      <div className="card-head">
        <Link to={`/book/${book.id}`} className="cover-link">
          <CoverImage
            className="thumb cursor-pointer"
            src={book.cover_url}
            title={book.title}
            alt={book.title}
          />
        </Link>
        <div className={!compact ? 'title-container' : ''}>
          <h3 className="title-text">{book.title}</h3>
          <p className="muted text-break">
            {truncateText(book.description)}
          </p>
          <div className="pill-row">
            <span className="pill">{STATUS[book.status] ?? book.status}</span>
            {book.score !== undefined && book.score !== null && book.score !== 0 ? (
              <span
                className="pill ghost"
                style={{ color: scoreColor(book.score), borderColor: scoreColor(book.score) }}
              >
                {scoreToLabel(book.score) || `Score: ${book.score}`}
              </span>
            ) : null}
            {!compact && book.language && (
              <span className="pill ghost emoji-text language-pill" title="Reading Language">
                {languageFlag(book.language) ? `${languageFlag(book.language)} ` : ''}
                {book.language}
              </span>
            )}
            {book.original_language && (
              <span className="pill ghost emoji-text original-language-pill" title="Original Language">
                {languageFlag(book.original_language) ? `${languageFlag(book.original_language)} ` : ''}
                {book.original_language}
              </span>
            )}
            {book.times_read !== undefined && book.times_read !== null && book.times_read > 1 && (
              <span className="pill ghost">Reads: {book.times_read}</span>
            )}
            {book.chapter_count !== undefined && book.chapter_count !== null && (
              <span className="pill ghost">Chapters: {book.chapter_count}</span>
            )}
            {!compact &&
              book.shelves?.map((shelfId) => {
                const shelf = customShelves.find((s) => s.id === shelfId)
                return shelf ? (
                  <span key={shelfId} className="pill shelf-indicator">
                    📚 {shelf.name}
                  </span>
                ) : null
              })}
          </div>
          {!compact && book.notes && (
            <p className="muted notes-text">
              📝 {book.notes}
            </p>
          )}
          {!compact && book.genres?.length > 0 && (
            <div className="pill-row genre-pills">
              {book.genres.map((g, i) => {
                const isActive = activeGenres.includes(g)
                return (
                  <button
                    key={`${g}-${i}`}
                    className={isActive ? 'pill' : 'pill ghost pill-small'}
                    onClick={() => {
                      if (setActiveGenres) {
                        setActiveGenres(
                          isActive ? activeGenres.filter((genre) => genre !== g) : [...activeGenres, g]
                        )
                      }
                    }}
                  >
                    {g}
                  </button>
                )
              })}
            </div>
          )}
        </div>
      </div>
      <div className="card-footer">
        <div>
          {book.last_read && book.status !== 'completed' && (
            <>
              <p className="muted">Last read</p>
              <p>{book.last_read}</p>
            </>
          )}
          <p className="muted" style={book.last_read && book.status !== 'completed' ? { marginTop: '8px' } : undefined}>Latest chapter</p>
          <p>{book.latest_chapter || '—'}</p>
          {!compact && book.last_uploaded_at && (
            <p className="muted upload-date">
              {new Date(book.last_uploaded_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
            </p>
          )}
        </div>
        <div className="card-links">
          {book.sources.slice(0, compact ? 2 : 1).map((source) => (
            <a
              key={source.url}
              href={source.url}
              target="_blank"
              rel="noreferrer"
              className="ghost"
            >
              {source.label}
            </a>
          ))}
          {!compact && customShelves.length > 0 && (
            <div className="shelf-menu-container">
                <div className="shelf-button-wrapper">
              <button
                className="ghost shelf-button"
                onClick={() => setShowShelfMenu(!showShelfMenu)}
              >
                + Shelf
              </button>
                </div>
              {showShelfMenu && (
                <div className="shelf-dropdown">
                  {customShelves.map((shelf) => {
                    const isInShelf = book.shelves?.includes(shelf.id)
                    return (
                      <button
                        key={shelf.id}
                        className="shelf-dropdown-item"
                        onClick={() => handleToggleShelf(shelf.id)}
                      >
                        <span>{isInShelf ? '✓' : '○'}</span>
                        <span>{shelf.name}</span>
                      </button>
                    )
                  })}
                </div>
              )}
            </div>
          )}
          <Link to={`/book/${book.id}`} className="primary">
            Details
          </Link>
        </div>
      </div>
    </article>
  )
}

export default BookCard

// angular/src/app/shared/components/book-card/book-card.component.ts
import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Book } from '../../../models/book.model';
import { Shelf } from '../../../models/shelf.model';
import { truncateText } from '../../utils/string.util';
import { CoverImageComponent } from '../cover-image/cover-image.component';

const SCORE_OPTIONS: Record<number, string> = {
  10: 'Masterpiece',
  9: 'Great',
  8: 'Pretty Good',
  7: 'Good',
  6: 'Fine',
  5: 'Average',
  4: 'Pretty Bad',
  3: 'Bad',
  2: 'Horrible',
  1: 'Appalling',
};

@Component({
  selector: 'app-book-card',
  standalone: true,
  imports: [CoverImageComponent, RouterLink],
  styleUrl: './book-card.component.scss',
  template: `
    <article class="card book-card" [class.compact]="compact()" [id]="'book-anchor-' + book().id">
      <div class="card-head">
        <a class="cover-link" [routerLink]="['/book', book().id]" (click)="opened.emit(book().id)">
          <app-cover-image class="thumb" [src]="book().coverUrl" [alt]="book().title" />
        </a>

        <div class="title-container">
          <h3 class="title-text">{{ book().title }}</h3>
          <p class="muted text-break">{{ truncateDescription(book().description) }}</p>

          <div class="pill-row">
            <span class="pill">{{ statusLabel(book().status) }}</span>

            @if (book().score; as score) {
              <span
                data-testid="score-pill"
                class="pill ghost"
                [style.color]="scoreColor(score)"
                [style.borderColor]="scoreColor(score)"
              >
                {{ scoreLabel(score) }}
              </span>
            }

            @if (!compact() && book().language; as lang) {
              <span data-testid="language-pill" class="pill ghost language-pill emoji-text" title="Reading Language">
                {{ formatLanguage(lang) }}
              </span>
            }

            @if (book().originalLanguage; as originalLanguage) {
              <span data-testid="original-language-pill" class="pill ghost original-language-pill emoji-text" title="Original Language">
                {{ formatLanguage(originalLanguage) }}
              </span>
            }

            @if (book().timesRead > 1) {
              <span data-testid="times-read-pill" class="pill ghost">Reads: {{ book().timesRead }}</span>
            }

            @if (book().chapterCount !== null) {
              <span data-testid="chapter-count-pill" class="pill ghost chapter-count-pill">Chapters: {{ book().chapterCount }}</span>
            }

            @if (!compact()) {
              @for (shelf of activeCustomShelves(); track shelf.id) {
                <span class="pill shelf-indicator">📚 {{ shelf.name }}</span>
              }
            }
          </div>

          @if (!compact()) {
            @if (book().notes; as notes) {
              <p data-testid="book-notes" class="muted notes-text">
                📝 {{ truncateText(notes) }}
              </p>
            }
          }

          @if (book().genres && book().genres.length > 0 && !compact()) {
            <div data-testid="genre-row" class="pill-row genre-row">
              @for (genre of book().genres; track genre) {
                <button
                  data-testid="genre-pill"
                  class="genre-pill"
                  [class.active]="activeGenres().includes(genre)"
                  (click)="genreToggled.emit(genre)"
                >
                  {{ genre }}
                </button>
              }
            </div>
          }
        </div>
      </div>

      <footer class="card-footer">
        <div>
          @if (book().lastRead && book().status !== 'completed') {
            <p class="muted">Last read</p>
            <p>{{ book().lastRead }}</p>
          }

          <p class="muted" [class.mt-8]="book().lastRead && book().status !== 'completed'">Latest chapter</p>
          <p data-testid="latest-chapter-value">{{ book().latestChapter || '—' }}</p>

          @if (!compact() && book().lastUploadedAt) {
            <p data-testid="last-uploaded" class="muted upload-date">{{ formatDate(book().lastUploadedAt) }}</p>
          }
        </div>

        <div class="card-links">
          @for (source of visibleSources(); track source.url) {
            <a data-testid="source-link" [attr.href]="source.url" target="_blank" rel="noreferrer" class="ghost">
              {{ sourceLabel(source.siteName) }}
            </a>
          }

          @if (customShelves().length > 0 && !compact()) {
            <div class="shelf-menu-container">
              <div class="shelf-button-wrapper">
              <button
                class="ghost shelf-button"
                data-testid="add-shelf-btn"
                type="button"
                (click)="showShelfMenu.set(!showShelfMenu())"
              >
                + Shelf
              </button>
              </div>

              @if (showShelfMenu()) {
                <ul data-testid="shelf-dropdown" class="shelf-dropdown">
                  @for (shelf of customShelves(); track shelf.id) {
                    <li
                      data-testid="shelf-item"
                      (click)="onShelfClick(shelf.id)"
                    >
                      <button class="shelf-dropdown-item" type="button" (click)="$event.stopPropagation(); onShelfClick(shelf.id)">
                        <span>{{ isBookOnShelf(shelf) ? '✓' : '○' }}</span>
                        <span>{{ shelf.name }}</span>
                      </button>
                    </li>
                  }
                </ul>
              }
            </div>
          }

          <a
            data-testid="book-detail-link"
            class="primary"
            [routerLink]="['/book', book().id]"
            (click)="opened.emit(book().id)"
          >
            Details
          </a>
        </div>
      </footer>
    </article>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BookCardComponent {
  readonly book = input.required<Book>();
  readonly activeGenres = input<string[]>([]);
  readonly customShelves = input<readonly Shelf[]>([]);
  readonly compact = input<boolean>(false);
  
  readonly opened = output<string>();
  readonly genreToggled = output<string>();
  readonly shelfToggled = output<{ bookId: string; shelfId: string }>();

  readonly showShelfMenu = signal(false);

  readonly activeCustomShelves = () => this.customShelves().filter((shelf) => this.isBookOnShelf(shelf));
  readonly visibleSources = () => {
    const sources = this.book().sources ?? [];
    return sources.slice(0, this.compact() ? 2 : 1);
  };

  sourceLabel(siteName: string | null | undefined): string {
    const label = (siteName ?? 'Source').trim() || 'Source';
    return label.length > 6 ? `${label.slice(0, 6)}...` : label;
  }

  statusLabel(status: Book['status']): string {
    const labels: Record<Book['status'], string> = {
      plan_to_read: 'Plan to read',
      reading: 'Reading',
      waiting: 'Waiting',
      completed: 'Completed',
      dropped: 'Dropped',
      on_hold: 'On hold',
    };

    return labels[status] ?? status;
  }

  scoreColor(score: number): string {
    if (score >= 9) return '#b34ad3';
    if (score >= 7) return '#0ba360';
    if (score >= 5) return '#c6a700';
    if (score >= 3) return '#d97706';
    return '#d14343';
  }

  scoreLabel(score: number): string {
    return SCORE_OPTIONS[score] ?? `Score: ${score}`;
  }

  formatLanguage(language: string): string {
    const lower = language.toLowerCase();
    let flag: string | null = null;

    if (lower.startsWith('eng') || lower === 'en' || lower === 'english') {
      flag = '🇬🇧';
    } else if (lower.startsWith('jap') || lower === 'jp' || lower === 'ja' || lower === 'jpn') {
      flag = '🇯🇵';
    } else if (lower.startsWith('kor') || lower === 'kr' || lower === 'ko') {
      flag = '🇰🇷';
    } else if (lower.startsWith('chi') || lower === 'cn' || lower === 'zh' || lower.includes('mandarin')) {
      flag = '🇨🇳';
    } else if (lower.startsWith('spa') || lower === 'es') {
      flag = '🇪🇸';
    }

    return flag ? `${flag} ${language}` : language;
  }

  truncateText(text: string): string {
    return truncateText(text);
  }

  truncateDescription(text: string): string {
    return truncateText(text, 15);
  }

  isBookOnShelf(shelf: Shelf): boolean {
    return shelf.bookIds?.includes(this.book().id) ?? false;
  }

  onShelfClick(shelfId: string): void {
    this.shelfToggled.emit({ bookId: this.book().id, shelfId });
    this.showShelfMenu.set(false);
  }

  formatDate(value: Date | null): string {
    if (!value) {
      return '—';
    }

    return value.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  }
}
